/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-02-18 22:11:37 UTC)
 * on 2016-03-03 at 21:29:19 UTC 
 * Modify at your own risk.
 */

package com.appspot.uppoint_api.uppointApi.model;

/**
 * Model definition for ProfessionPayload.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Uppoint API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ProfessionPayload extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String categoryKey;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String key;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<LocalePair> translation;

  static {
    // hack to force ProGuard to consider LocalePair used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(LocalePair.class);
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCategoryKey() {
    return categoryKey;
  }

  /**
   * @param categoryKey categoryKey or {@code null} for none
   */
  public ProfessionPayload setCategoryKey(java.lang.String categoryKey) {
    this.categoryKey = categoryKey;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getKey() {
    return key;
  }

  /**
   * @param key key or {@code null} for none
   */
  public ProfessionPayload setKey(java.lang.String key) {
    this.key = key;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<LocalePair> getTranslation() {
    return translation;
  }

  /**
   * @param translation translation or {@code null} for none
   */
  public ProfessionPayload setTranslation(java.util.List<LocalePair> translation) {
    this.translation = translation;
    return this;
  }

  @Override
  public ProfessionPayload set(String fieldName, Object value) {
    return (ProfessionPayload) super.set(fieldName, value);
  }

  @Override
  public ProfessionPayload clone() {
    return (ProfessionPayload) super.clone();
  }

}
